apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: rest
      port: 8081
  selector:
    app: flink
    component: jobmanager
